### ISSUE TITLE
Export defined fields from documents only

### ISSUE THREAD

**Issue by vhugogarcia** [davr59/firestore-json-export-import#5]
Hello @davr59,

First, I would like to tHANK YOU for this wrapper to export/import firebase cloud firestore. I'm wondering if it is possible under schema.js set the fields of the documents, I want to export only the fields we need and this way reduce the cluttering of all that data such as: _converter, _firestore, _clientPool, etc.

Thanks in advance.

**Comment by davr59** [comment]
Hello @vhugogarcia, you are welcome, glad to help. 
I just checked and there is a select function for specifying which fields you want to get from firestore.

In firestore2json.js (line 18, 19) I can add a select for only the fields specified in the schema.

Example: (in this example I hardcoded 'code' and 'name' just for the explanation, this should be get from the schema).
`Object.keys(_schema).map((collection) => db.collection(collection).select('code', 'name').get()`


And in the schema something like this for this example:
`
const schema = {
  inventory: {
    code: '',
    name: '',
  },
};
`

What do you think? Would it work for you?

**Comment by vhugogarcia** [comment]
Thanks @davr59 for your faster response. 

I think it make sense a lot. That will be really cool! And what about the reference type fields? How are those fields going to be exported?

For example, look at this document sample I have on my firebase:
![image](https://user-images.githubusercontent.com/1047398/86125526-6d555a80-baa2-11ea-8d17-a45be29e0f6f.jpeg)

As you can see my user document has only 4 fields: 
Cluster: reference field
Email: string
Role: reference field
Location: reference field

So, I am wondering how the export is going to work with those fields, so when we import it, the document keeps clean as it is on the screenshot.  

Let me know what you think

Thank you so much for the help

Regards,
Victor

**Comment by davr59** [comment]
Hey Victor. 
Sorry I was kind of busy with some work. I didn't think about reference types. I will do some testing to see how it goes with those types.

**Comment by vhugogarcia** [comment]
Hello my friend. No worries. Thank you so much for checking in.

**Comment by davr59** [comment]
Hello Victor.
I think I understand now the issue. Could you test with #6 **(backup your data first just in case)** to see if this works for you. Now it checks if it is a reference type and if it is, then only the reference path is exported. Import also takes this into account now.

**Comment by vhugogarcia** [comment]
Thanks @davr59 . I will take a look 😃

**Comment by vhugogarcia** [comment]
Hello @davr59 , I would like to say THANK YOU! now it exports the path only, correctly. And now in the import it also imports the data. However, there are 2 little things here:

1. I'm getting an error when importing:
`firestore-json-export-import-issue5-export-import-references vhugo$ npm run-script import

> firestore-json-export-import@1.0.1 import /Users/vhugo/Downloads/firestore-json-export-import-issue5-export-import-references
> node example-json2firestore.js

(node:25612) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Promise.all.Object.keys.map (/Users/vhugo/Downloads/firestore-json-export-import-issue5-export-import-references/json2firestore.js:11:16)
    at Array.map (<anonymous>)
    at j2f (/Users/vhugo/Downloads/firestore-json-export-import-issue5-export-import-references/json2firestore.js:9:28)
    at promises.push.db.collection.doc.set.then (/Users/vhugo/Downloads/firestore-json-export-import-issue5-export-import-references/json2firestore.js:27:17)
(node:25612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

2. How can I set on the schema.js subcollections to be dynamic since the UID is set custom by me without being auto-generated by Firebase. For example: I have a collection called: Clusters > Name > Locations > Address 1, Address XZY, etc. Also those name of locations have a sub-collection named: People, how can I then backup all of them? should I put the name of all custom locations in the schema.js file? Example of a path: **/clusters/name/locations/name_XYZ/people**


Thanks again for your hard work. It worked very good about the reference fields and when importing as well, it was a clean export and clean import on Firebase.

**Comment by davr59** [comment]
Didn't see your reply sorry. 
1. Could it be related to order in the schema.js? I noticed that you need to declare first the referenced ones and then the ones that have the references.
2. I haven't used subcollections. Let me play with it this week and I let you know how can we do it.

**Comment by davr59** [comment]
hey @vhugogarcia. I fixed issue number 1. Now I am working on number 2.

**Comment by vhugogarcia** [comment]
Great news! Thank you so much for your help with it.

**Comment by davr59** [comment]
@vhugogarcia I think number 2 is already working. 
You need to add the subcollections in the schema like this:

    const schema = {
        collection1: {
            subcollection1: {},
            subcollection2: {},
        },
    };

Let me know if it works for you.

**Comment by vhugogarcia** [comment]
Awesome! I will give it a try this weekend. 

Thank you @davr59 for your help with all these. It will for sure help us with the Cloud Firestore to perform local backups.

**Comment by davr59** [comment]
@vhugogarcia I used this code also to close other PR so it closed automatically. Still if you find something, let me know. Thanks.

**Comment by vhugogarcia** [comment]
Thank you so much. I am so sorry for the delay. I got busy. I will run a final test with all merged 😀
