### ISSUE TITLE
Export and import GeoPoint Type.

### ISSUE THREAD

**Issue by sc-cmendoza** [davr59/firestore-json-export-import#9]
There is a way to import my geopoint data?

**Comment by davr59** [comment]
Hey @sc-cmendoza sorry I didn't see this message. I was testing this case and right now it confuses geopoint with maps but I believe is easy to fix. Let me try a little bit and I will let you know.

**Comment by davr59** [comment]
Hello @sc-cmendoza 
I think I got it. Could you test with #10  (backup your data first just in case) to see if this works for you.

Geopoint data should look like this in the json file:
```
"geopointName": {
        "_latitude": 9.484296,,
        "_longitude": -83.488921
 },
```

**Comment by sc-cmendoza** [comment]
> Hello @sc-cmendoza
> I think I got it. Could you test with #10 (backup your data first just in case) to see if this works for you.
> 
> Geopoint data should look like this in the json file:
> 
> ```
> "geopointName": {
>         "_latitude": 9.484296,,
>         "_longitude": -83.488921
>  },
> ```

It works. Thanks!

**Comment by davr59** [comment]
Excellent!
